language: swift
osx_image: xcode11

branches:
  only:
  - master
  - dev

before_install:
  - gem install xcpretty -N
  - brew install swiftlint | true
script:
  - set -o pipefail
  - xcodebuild -workspace TimeZonePickerExample/TimeZonePickerExample.xcworkspace -scheme TimeZonePicker -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - xcodebuild test -workspace TimeZonePickerExample/TimeZonePickerExample.xcworkspace -scheme TimeZonePicker -destination "platform=iOS Simulator,name=iPhone 7,OS=latest" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - swiftlint